### ISSUE TITLE
No version number on generated library

### ISSUE THREAD

**Issue by rtb21** [leap71/PicoGKRuntime#15]
Even though `CMakeLists.txt` states that version numbers will be appended to the library name for unix-like systems (ln 62) this doesn't work for me and I'm getting a library named just `picogk.so`. Note that I'm also modifying the `CMakeLists.txt` as described in [issue 14](https://github.com/leap71/PicoGKRuntime/issues/14) which might change things? (I'm no expert on CMake!)

Building using clang 14.0.0 on Ubuntu 22.04

**Comment by LinKayser** [comment]
I haven't tried this on LINUX — one of these days, I'll have a look. 

At least on Mac, the version number is automatically appended, that's why the CMakeLists.txt contains the following conditional statement:

```
# Define the library name
if( WIN32 )
	set(LIB_NAME "picogk.${LIB_VERSION_MAJOR}.${LIB_VERSION_MINOR}")
else()
	# unix-like systems automatically append version number
	set(LIB_NAME "picogk")
endif()
```

You could experiment with commenting out the conditional and see if you get the desired result.

Best,
Lin
