### ISSUE TITLE
GLFW as git submodule + cmake version

### ISSUE THREAD

**Issue by drlukeparry** [leap71/PicoGKRuntime#2]
Is it possible to make the glfw source as a git submodule component, rather than rely on retrieving the repository via cmake? The build script failed to retrieve the repository on Mac OSX Sonoma.

We already have to initialise the submodules for openVDB so it would seem sensible that it could be done for GLFW library.

Finally, is it necessary to have the latest version of cmake at v3.27? Is it a prerequisite for compiling the static library for openVDB?

**Comment by LinKayser** [comment]
It's the CMake version we use and it's good practice to specify the used version as minimum (as you cannot guarantee it to work with a version you have never used). I am sure it works with lesser versions, but I haven't tested it.

As for the submodule, sure, it could be done. Not sure why it would fail, though. If you make it work with a submodule, feel free to submit a pull request. I can check it out for one of the next versions, otherwise.
